### ISSUE TITLE
Avance del proyecto

### ISSUE THREAD

**Issue by aguzro** [scarleette/scl-2018-05-bc-core-pm-datadashboard#1]
Hola! Vengo a dar feedback! 💃 

-  Prototipos: El sketch está bastante bien, aunque me hubiera gustado ver más detalle, quizás una interacción en cuanto a los contenidos que irían dentro del prototipo, pero la interacción queda bastante clara. En cuanto al de alta fidelidad, no veo todas las acciones que describen en el sketch, recueda que es importante que el prototipo de alta fidelidad sea lo más verídico a lo que se verá en cuanto a código.

- Código: No veo que realizaras mucho, quedan pocos días!! Ponganle para que alcancen a llegar para el viernes 👯

**Comment by scarleette** [comment]
ali , el modelo de alta fidelidad es animado creo que lo explico en el readme si muestra interacción, si no no entiendo muy bien el que debería parecerse  mucho mas al de baja fidelidad.
